### ISSUE TITLE
Valid EAN-13 (based on other online checkers) returns as not valid

### ISSUE THREAD

**Issue by judgej** [hitmeister/gtin-validator#12]
Tried this:

    Real\Validator\Gtin\Factory::isValid('0231566199093')

and I get `false`. This should be a valid EAN-13 and a GTIN-13, derived from a UPC-12 with its "0" prefix and recalculated check digit.

I expected that to be valid. Should it not be valid? Is there some group range in this GTIN-13 that makes it invalid?

**Comment by radarlog** [comment]
Thank you for the report.

A 13-digit code beginning with a zero is technically not a GTIN-13, but is instead a GTIN-12 or GTIN-8 padded to 13 digits, in your particular case GTIN-12. The prefix of this GTIN is `023` and as far as I [see](https://www.gs1.org/standards/id-keys/company-prefix), it's used to issue Restricted Circulation Numbers within a geographic region (MO defined).

Currently it's [commented](https://github.com/real-digital/gtin-validator/blob/master/src/Gtin/Specification/Prefix.php#L134) out. I'm going to revise all prefixes due to fresh changes of this specification

Just out of my curiosity where have you faced such GTIN?

**Comment by judgej** [comment]
The way I understand it, a UPC is GTIN, and that is 12 digits long, but US based. A UPC can be converted to an EAN by adding the country code, a zero in this case. So any UPC can be a 13 digit EAN, with no check digit change needed. And an EAN is a GTIN.

I may have any of those things wrong, but my starting point is that any EAN, any UPC, and any ISBN-13, is also a GTIN.

**Comment by radarlog** [comment]
> The way I understand it, a UPC is GTIN, and that is 12 digits long, but US based. A UPC can be converted to an EAN by adding the country code, a zero in this case. So any UPC can be a 13 digit EAN, with no check digit change needed. And an EAN is a GTIN.

Not exactly, [here](https://github.com/real-digital/gtin-validator/blob/master/src/Gtin.php) you can find some insights.

> I may have any of those things wrong, but my starting point is that any EAN, any UPC, and any ISBN-13, is also a GTIN.

that's correct as GTIN is superset of EAN and UPC as well as ISBN and ISSN

**Comment by judgej** [comment]
I was going off articles such as this, where a supplied UPC is guaranteed to have a unique EAN available by adding the zero:

https://www.nationwidebarcode.com/combining-ean-and-upc-barcodes/

Maybe that only applies to certain ranges of UPC? Presumably you would need to apply for both the UPC and the EAN separately, but the EAN would be affectively reserved for [all?] UPCs.

Are there any examples of when a UPC `XXXXXXXXXXXX` would be a different product to EAN `0XXXXXXXXXXXX`?
