### ISSUE TITLE
Valid EAN-13 (based on other online checkers) returns as not valid

### ISSUE THREAD

**Issue by rusavskiy** [hitmeister/gtin-validator#14]
Hi.
Check - 718 037 837 642 6
`\Real\Validator\Gtin\Factory::isValid("7180378376426") == false` but online in https://www.gs1.org/services/check-digit-calculator or https://www.getnewidentity.com/validate-ean.php?ean=7180378376426

**Comment by radarlog** [comment]
Hi :wave: 

thank you for the report.

The first [link](gs1.org/services/check-digit-calculator ) you provided can only calculate the check digit, which in your case is equal to `6`, so there are no issues from this perspective.

Current library actually complains about the wrong prefix, which in your case is `718`. As far as I see, it is not explicitly listed in the [table](https://www.gs1.org/standards/id-keys/company-prefix), meaning the prefix is reserved for future use (please see notes at the page).

That's why the mentioned GTIN reasonably does not pass validation.

Unfortunately, I do not know how strictly 3rd party [services](getnewidentity.com/validate-ean.php?ean=7180378376426) and libraries follow the GTIN specifications. Probably, it makes sense to ask them directly.

**Comment by rusavskiy** [comment]
Ok. Thank you.
